---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
    tier: db
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: prawien/mysql:k8
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---